// <auto-generated />
using APIPedidos.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace APIPedidos.Migrations
{
    [DbContext(typeof(PedidosDbContext))]
    [Migration("20260919223000_CascadeDeleteClientePedidos")]
    partial class CascadeDeleteClientePedidos
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");
        }
    }
}
